#!/usr/bin/python3
"""RSA factoring problem"""
import sys
from sympy import factorint


def factorize(n):
    """Factorize n"""
    factors = factorint(n)
    return factors.items()


def main():
    """Main function"""
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    filename = sys.argv[1]
    try:
        with open(filename, 'r') as file:
            numbers = file.readlines()
            for number in numbers:
                n = int(number.strip())
                factors = factorize(n)
                factorization = ' * '.join(
                    [f'{factor}^{exponent}' for factor, exponent in factors])
                print(f"{n} = {factorization}")
    except FileNotFoundError:
        print(f"File '{filename}' not found.")


if __name__ == '__main__':
    main()
